# Домашнє завдання 6
## Аналіз набору даних фільмів

### 1. Завантаження даних

In [1]:

import os
import requests
import pandas as pd

url = "https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv"
file_name = "movies.csv"

if not os.path.exists(file_name):
    response = requests.get(url)
    if response.status_code == 200:
        with open(file_name, "wb") as f:
            f.write(response.content)

df = pd.read_csv(file_name)
df = df.drop_duplicates()
df.head()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008

### 2. Огляд структури та статистики

In [2]:

df.columns

Index(['Film', 'Genre', 'Lead Studio', 'Audience score %', 'Profitability',
       'Rotten Tomatoes %', 'Worldwide Gross', 'Year'],
      dtype='str')

In [3]:

df.dtypes

Film                     str
Genre                    str
Lead Studio              str
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross          str
Year                   int64
dtype: object

In [4]:

df.info()

<class 'pandas.DataFrame'>
Index: 75 entries, 0 to 76
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               75 non-null     str
 1   Genre              75 non-null     str
 2   Lead Studio        75 non-null     str
 3   Audience score %   75 non-null     int64
 4   Profitability      75 non-null     float64
 5   Rotten Tomatoes %  75 non-null     int64
 6   Worldwide Gross    75 non-null     str
 7   Year               75 non-null     int64
dtypes: float64(1), int64(3), str(4)
memory usage: 5.3 KB

In [5]:

df.describe()

       Audience score %  Profitability  Rotten Tomatoes %         Year
count         75.000000      75.000000          75.000000    75.000000
mean          63.720000       4.527171          46.493333  2009.066667
std           13.699043       8.121111          26.412207     1.349007
min           35.000000       0.000000           3.000000  2007.000000
25%           52.000000       1.749447          26.000000  2008.000000
50%           64.000000       2.639333          43.000000  2009.000000
75%           75.000000       4.535337          64.500000  2010.000000
max           89.000000      66.934000          96.000000  2011.000000

### 3. Кількість фільмів

In [6]:

df.shape[0]

75

### 4. Кількість фільмів за роками

In [7]:

df['Year'].value_counts().sort_index()

Year
2007    11
2008    19
2009    12
2010    20
2011    13
Name: count, dtype: int64

### 5. Найбільш та найменш прибуткові фільми

In [8]:

df[df['Profitability'] == df['Profitability'].max()]

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
68,Fireproof,Drama,Independent,51,66.934,40,$33.47,2008

In [9]:

df[df['Profitability'] == df['Profitability'].min()]

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
3,When in Rome,Comedy,Disney,44,0.0,15,$43.04,2010
33,Our Family Wedding,Comedy,Independent,49,0.0,14,$21.37,2010
57,Jane Eyre,Romance,Universal,77,0.0,85,$30.15,2011

### 6. Виправлення жанрів

In [10]:

df['Genre'].unique()

<StringArray>
[  'Romance',    'Comedy',     'Drama', 'Animation',   'Fantasy',   'Romence',
     'Comdy',    'Action',   'romance',    'comedy']
Length: 10, dtype: str

In [13]:

df['Genre'] = df['Genre'].replace({
    'romance': 'Romance',
    'Romence': 'Romance',
    'comedy': 'Comedy',
    'Comdy': 'Comedy'
})
df['Genre'].unique()

<StringArray>
['Romance', 'Comedy', 'Drama', 'Animation', 'Fantasy', 'Action']
Length: 6, dtype: str

### 7. Топ-10 комедій

In [18]:

top_comedy = (
    df[df['Genre'] == 'Comedy']
    .sort_values('Audience score %', ascending=False)
    .head(10)[['Film', 'Year', 'Lead Studio']]
)

top_comedy.to_csv("top_10_comedy.csv", index=False)
top_comedy

                                  Film  Year   Lead Studio
54                          Knocked Up  2007     Universal
27                    Sex and the City  2008  Warner Bros.
76                (500) Days of Summer  2009           Fox
69                           Enchanted  2007        Disney
71                           Beginners  2011   Independent
44                       Marley and Me  2008           Fox
60  High School Musical 3: Senior Year  2008        Disney
45                          Mamma Mia!  2008     Universal
16                        The Proposal  2009        Disney
30                            Penelope  2008        Summit

### 8. Встановлення бібліотек

In [19]:

!pip install lxml mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.0.3-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Downloading lxml-6.0.3-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------- ----------- 2.9/4.1 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 14.4 MB/s  0:00:00
Downloading mysql_connector_python-9.6.0-cp314-cp314-win_amd64.whl (17.0 MB)
   ---------------------------------------- 0.0/17.0 MB ? eta -:--:--
   --------------- ------------------------ 6.6/17.0 MB 29.9 MB/s eta 0:00:01
   ----------------------------- ---------- 12.6/17.0 MB 30.2 MB/s eta 0:00:01
   ---------------------------------------- 17.0/17.0 MB 26.9 MB/s  0:00:00
Installing collected packages: mysql-connector-python, lxml

   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   ---------------------------------------- 0/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [lxml]
   -------------------- ------------------- 1/2 [lxml]
   -------------------- ------------------- 1/2 [lxml]
   -------------------- ------------------- 1/2 [lxml]
   -------------------- ------------------- 1/2 [lxml]
   -------------------- ------------------- 1/2 [lxml]
   ---------------------------------------- 2/2 [lxml]

Successfully installed lxml-6.0.3 mysql-connector-python-9.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip